In [ ]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('Churn_Modelling.csv',index_col= 'RowNumber')
# print(dataset)
X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])
X


array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
X[0]

array([1.0, 0.0, 0.0, 619, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [ ]:
le_1 = LabelEncoder()
X[:, 4] = le_1.fit_transform(X[:, 4])
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, train_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
import tensorflow as tf


ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# ann.compile(optimizer='sgd', loss=tf.keras.losses.SquaredHinge(), metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 100, epochs = 50)

Epoch 1/50
20/20 [==============================] - 1s 4ms/step - loss: 0.6291 - accuracy: 0.6555
Epoch 2/50
20/20 [==============================] - 0s 4ms/step - loss: 0.5963 - accuracy: 0.7255
Epoch 3/50
20/20 [==============================] - 0s 5ms/step - loss: 0.5688 - accuracy: 0.7730
Epoch 4/50
20/20 [==============================] - 0s 6ms/step - loss: 0.5468 - accuracy: 0.7925
Epoch 5/50
20/20 [==============================] - 0s 5ms/step - loss: 0.5283 - accuracy: 0.7990
Epoch 6/50
20/20 [==============================] - 0s 4ms/step - loss: 0.5129 - accuracy: 0.7985
Epoch 7/50
20/20 [==============================] - 0s 3ms/step - loss: 0.5004 - accuracy: 0.7990
Epoch 8/50
20/20 [==============================] - 0s 4ms/step - loss: 0.4901 - accuracy: 0.8005
Epoch 9/50
20/20 [==============================] - 0s 4ms/step - loss: 0.4810 - accuracy: 0.8015
Epoch 10/50
20/20 [==============================] - 0s 6ms/step - loss: 0.4732 - accuracy: 0.8010
Epoch 11/50
20/20 [

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[6046  318]
 [ 933  703]]


0.843625